metilene -a NN -b UC -m 5 ./raw/chr1_metiline.tab > ./results/chr1_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr10_metiline.tab > ./results/chr10_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr11_metiline.tab > ./results/chr11_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr12_metiline.tab > ./results/chr12_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr13_metiline.tab > ./results/chr13_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr14_metiline.tab > ./results/chr14_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr15_metiline.tab > ./results/chr15_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr16_metiline.tab > ./results/chr16_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr17_metiline.tab > ./results/chr17_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr18_metiline.tab > ./results/chr18_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr19_metiline.tab > ./results/chr19_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr2_metiline.tab > ./results/chr2_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr20_metiline.tab > ./results/chr20_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr21_metiline.tab > ./results/chr21_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr22_metiline.tab > ./results/chr22_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr3_metiline.tab > ./results/chr3_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr4_metiline.tab > ./results/chr4_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr5_metiline.tab > ./results/chr5_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr6_metiline.tab > ./results/chr6_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr7_metiline.tab > ./results/chr7_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr8_metiline.tab > ./results/chr8_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chr9_metiline.tab > ./results/chr9_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chrM_metiline.tab > ./results/chrM_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chrX_metiline.tab > ./results/chrX_met_result.tab 
metilene -a NN -b UC -m 5 ./raw/chrY_metiline.tab > ./results/chrY_met_result.tab 
